inference:
    # Tensorflow inception model directory.
    model_dir: /path/to/ip-camera-image-inference/model
    # Images classified as person are always published to the MQTT broker.
    # Define a probability threshold for all other images you also want to
    # publish to the MQTT broker.
    threshold: 0.80
mqtt:
    # MQTT broker connection settings.
    host: 192.168.1.50
    port: 1883
    username: username
    password: password
    # Subscribe to this topic to receive images.
    subscribe_topic: ipcamera/inference/front
    # Publish to this topic after classification.
    publish_topic: ipcamera/sc/front
save_images:
    # Save all images not published to the MQTT broker.
    # Useful for debugging purposes.
    enabled: true
    destination: /path/to/ip-camera-image-inference/rejected-images

logging:
    filename: image-inference.log
    level: DEBUG
